### ISSUE TITLE
consider bumping pedantic by major versions when adding a lint

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/pedantic#21]
I've seen CIs for several projects break after the release of the latest `package:pedantic` - v`1.6.0`.

In the readme for this project, I see:

> This example uses a pinned version because every added lint rule could break a build for projects using it.

You might consider either
- making this more explicit - only recommend that consumers use specific versions, or pin to narrow ranges (`>=1.5.0 <1.6.0`).
- or, only make pedantic more restrictive - adding more rules - on upgrades to major versions. That would allow projects to use deps like `^1.0.0` and adjust to new versions of pedantic at a more leisurely pace. That would probably also follow the guidance of semver more closely.

**Comment by davidmorgan** [comment]
There's actually a nasty problem here :/ ... because we have conflated the analysis options with the tiny amount of code in `lib/pedantic.dart`.

`dev_dependencies` are not a problem, but anyone using `unawaited` needs a normal dependency. If two packages both use `unawaited`, and want different pinned versions of lints, then they can't be used together. They will be forced to move to the same version of the lints, first.

Here's one possible solution. We could include all versions of the analysis options in the package:

  `lib/analysis_options.1.2.0.yaml`
  `lib/analysis_options.1.3.0.yaml`
  `lib/analysis_options.1.4.0.yaml`

then, also include an `analysis_options.yaml` file that points to the latest version. So for most people behaviour is unchanged. If you want to `pin` your analysis options version, you do that by including a specific yaml file; it's no longer anything to do with pub.

What do you think?

**Comment by a14n** [comment]
An other option would be to publish an other package containing only the yaml file.

* `pedantic` for `unawaited`...
* `pedantic_yaml` (or something else) for `analysis_options.yaml` - this package will be used exclusively in `dev_dependencies` and every change can be released by bumping its major version.

**Comment by davidmorgan** [comment]
Yes. I'm not a huge fan of the idea, partly because of overhead in migrating to and maintaining an additional package, and partly because the yaml files don't really seem to fit with pub: they're not dart code, and every new version is incompatible.

But it would solve the problem :)

**Comment by devoncarew** [comment]
Having versioned sets of analysis options files seems great - it would let projects pin on specific versions, and migrate to new ones as they wanted to.

**Comment by grouma** [comment]
I'll be a voice in the other direction on this one. It's definitely annoying that changes to `package:pedantic` can break our packages. However, these breaks are often trivial to fix and are a good alert that there is a new standard to adopt. I don't see us actively upgrading to the newer lints otherwise. If we really want to enable users to pin to a version I suggest providing `lib/analysis_options.latest.yaml` or something.

**Comment by pq** [comment]
One reason ***not*** to pin versions is if you care about your pana scoring.  I'm guessing there you'll always be graded on latest? (@jonasfj?)

Awareness of new rules is a known, acute but as of yet unsolved problem.  😬  (See also: https://github.com/dart-lang/linter/issues/1390.)

**Comment by jakemac53** [comment]
+1 for providing versioned files with the regular `analysis_options.yaml` as an alias for the latest one.

That allows you to keep up with the latest lints, while also providing a low friction path to temporarily pinning to a previous version if you don't have time to update immediately when you get broken by the new lints.

**Comment by davidmorgan** [comment]
Thanks for the input everyone. Let's see how this works. I think giving people choice makes sense--the default is still to pin to head, but I know that will annoy some people, particularly on big projects.
