### ISSUE TITLE
unawaited with void return

### ISSUE THREAD

**Issue by jklint-g** [dart-lang/pedantic#29]
The unawaited check doesn't flag calls to async methods which return plain void rather than Future\<void\>, ie:

```
void main() async {
  try {
    doThing(); // No unawaited error here
  } catch (e) {
    print("caught $e");
  }
}

// Returns void instead of Future<void>
void doThing() async {
  await Future.delayed(Duration(seconds: 1));
  throw Exception("oops");
}
```

I'm not really clear on the semantics of returning void instead of Future<void> from doThing(). IIRC the compiler used to always require returning a Future from async methods and at some point changed to allow just void, but that still seems to function as an awaitable future.

In the example above, awaiting doThing() results in the exception being caught while not awaiting does not.

Seems like this should be flagged?

**Comment by eernstg** [comment]
The ability to return `void` from an async method was included because it can be used to indicate that the caller _should not_ await the returned future. That is, it is a "fire and forget" operation. It will return a `Future` (as all async functions do), but the type `void` says that it should be ignored.

It could make sense to lint this situation because it is too easy to get to such a function by editing an existing void function to make it `async`, and then forgetting to change the return type to `Future<void>`. Also, "fire and forget" functions could be so rare that it's reasonable to assume that they arise by mistake, and then the ones that should really be "fire and forget" can be marked with an 'ignore' comment, and presumably also a human-readable comment explaining that this operation should not be `await`ed.

**Comment by a14n** [comment]
There's the lint [avoid_void_async](https://dart-lang.github.io/linter/lints/avoid_void_async.html) to prevent `void` return type in `async` functions.

**Comment by davidmorgan** [comment]
The fact that awaiting a void async function has an effect is a known issue; it would be better if it did not do anything, i.e. did not await, but that would have been a breaking change and it was deemed too hard to land.

The way to get the correct behaviour is to also enforce

https://dart-lang.github.io/linter/lints/await_only_futures.html

--which we do not yet have in the `pedantic` lint list, but we expect to at some point.

**Comment by jklint-g** [comment]
Thanks for all the input! `avoid_void_async` looks very helpful as my biggest concern is the accidental instances of returning only `void` as eernstg described.

For instance, in our app codebase the async method return type is split about 50-50 between `Future<void>` vs `void`, and I am very skeptical that half of our async methods were intentionally meant as fire-and-forget.

Fire-and-forget seems useful in specific circumstances, it's just terribly easy to end up doing this accidentally. Since `avoid_void_async` is a hard rule which eliminates this construct, it might be helpful to have a middle-ground pedantic option which forces the caller to explicitly acknowledge they are firing and forgetting (although "unawaited" may not be the best term here since it sounds like `await_only_futures` will render these calls unawaitable anyways).

Consider this a feature request and feel free to close it out if the team disagrees. The linter options above will help solve my immediate concern.

**Comment by davidmorgan** [comment]
Hmm, that's an API design issue, though, not something on the caller.

We could have a lint that warns if an async method returns `void`. But, this is sometimes what you actually want. Currently pedantic only has fully enabled lints and fully disabled lints; we don't have a category for 'advice you'd like to hear'. I want to figure out a good way to do that at some point, though :)

**Comment by matanlurey** [comment]
Closed as stale, I don't think we are changing this at the moment.
